### ISSUE TITLE
Doesn't like to load with Antagonist

### ISSUE THREAD

**Issue by hepkat** [laytya/EQCompare-Vanilla#1]
[2017/04/03 02:16:57-434]: EQCompare\EQCompare.lua:460: attempt to perform arithmetic on a boolean value
AceAddon-2.0\AceAddon-2.0.lua:595: in function `obj_method'
AceEvent-2.0\AceEvent-2.0.lua:247: in function `TriggerEvent'
AceEvent-2.0\AceEvent-2.0.lua:902: in function <...AddOns\Antagonist\libs\AceEvent-2.0\AceEvent-2.0.lua:894>

  ---

**Comment by laytya** [comment]
Update Antagonist libs from here https://github.com/laytya/Ace2
