### ISSUE TITLE
Disabled eqcompare module in pfUI and still this happens

### ISSUE THREAD

**Issue by hepkat** [laytya/EQCompare-Vanilla#2]
[2017/04/03 02:21:54-436]: modules\skin.lua:72: Usage: ShoppingTooltip1:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
<in C code>: in function `SetPoint'
modules\skin.lua:72: in function <Interface\AddOns\pfUI\modules\skin.lua:68>
<in C code>: in function `SetInventoryItem'
EQCompare\EQCompare.lua:226: in function <Interface\AddOns\EQCompare\EQCompare.lua:181>
<unknown>:
<in C code>: in function `SetBagItem'
FrameXML\ContainerFrame.lua:622: in function <Interface\FrameXML\ContainerFrame.lua:602>
QuestItem\QuestItemTooltip.lua:245: in function `ContainerFrameItemButton_OnEnter'
FrameXML\ContainerFrame.lua:658: in function `ContainerFrameItemButton_OnUpdate'
<string>:"pfBag0item16:OnUpdate":2: in main chunk

  ---

**Comment by hepkat** [comment]
Was throwing errors with other addons, but errors went away with pfUI disabled and those addons on. I'm guessing it's fighting with pfUI over skinning the tooltip.

**Comment by laytya** [comment]
pfUI fixed
https://forum.elysium-project.org/topic/43548-addon-eqcompare-vanilla/?do=findComment&comment=376241
